### ISSUE TITLE
review completed

### ISSUE THREAD

**Issue by hatelove** [mystic01/PotterShoppingCart#1]
幾點建議：

- 在第三個綠燈時，寫了太多太複雜的程式碼，步子邁太大，語意也不清楚
- 後面拉竿不回來，最大的問題還是在一開始的 API 設計，把幾個資訊拆散在多個 Dictionary 上，所以不容易做。語意不清楚的另一個原因，也是因為看到一堆 Key, Value, Max, Min。
- 最後版本的 production code 還是有很多改善空間的

---
sample solution 參考: https://github.com/hatelove/PotterShoppingCart/commits/anotherRefactor
我的演算法也寫得不夠好， 但對外的 function 主流程很清楚：

1. 防呆
2. 整理出有幾套書
3. 加總每一套折扣完的總價

[2017 新版 production code 作法](https://github.com/hatelove/PotterShoppingCart2017/commits/master) (中間過程因為一些緣故有漏 commit 檔案)

**Comment by mystic01** [comment]
謝謝 91 大指教，如同我在某個[ commit ](https://github.com/mystic01/PotterShoppingCart/commit/95b505e4febe690118556c238c2e98e35f2e1f91)所述～

之前好像搞錯了很多需求的意思

作為練習，我又重寫了一次作業

https://github.com/mystic01/PotterShoppingCart2

誠摯希望不要用死亡筆記本簽到  <(_ _)>
